name: PR Validation
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR author is a code owner
        id: check_codeowner
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const codeOwners = process.env.CODEOWNERS.split(',');
            const isAuthorCodeOwner = codeOwners.includes(pr.user.login);
            return isAuthorCodeOwner;

      - name: Validate Approvals
        if: ${{ steps.check_codeowner.outputs.result == 'false' }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            const codeOwners = process.env.CODEOWNERS.split(',');
            const approvals = reviews.data.filter(r => r.state === 'APPROVED');
            const hasCodeOwnerApproval = approvals.some(a => codeOwners.includes(a.user.login));

            if (approvals.length < 2 || !hasCodeOwnerApproval) {
              core.setFailed('PR cần ít nhất 2 approvals, trong đó 1 từ code owner.');
            }
